name: "Publish images"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      USER: jaegertracing
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
    - uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0
    - name: "publishes the images"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        OPERATOR_VERSION: main
      run: ./.ci/publish-images.sh
